#!/bin/bash
style=$(echo $1 | sed 's/^--//')
shift
emacs -q -batch -L $(dirname $0) \
    -l muse.el -l muse-publish.el \
    -l muse-html.el -l muse-latex.el -l muse-texinfo.el \
    -f muse-batch-publish-files $style --output-dir=. "$@"
