#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/muse

# Written by Jim Van Zandt <jrv@vanzandt.mv.com>, borrowing heavily
# from the install scripts for gettext by Santiago Vila
# <sanvila@ctv.es> and octave by Dirk Eddelbuettel <edd@debian.org>.

FLAVOR=$1
PACKAGE=muse-el

if [ ${FLAVOR} = emacs ]; then exit 0; fi

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

FLAVORTEST=`echo $FLAVOR | cut -c-6`
if [ ${FLAVORTEST} = xemacs ] ; then
    SITEFLAG="-no-site-file"
else
    SITEFLAG="--no-site-file"
fi
FLAGS="${SITEFLAG} -q -batch -l path.el -f batch-byte-compile"
ELPREFIX=/usr/share/emacs/site-lisp/${PACKAGE}

for i in ${PACKAGE} ${PACKAGE}/contrib; do

    ELDIR=/usr/share/emacs/site-lisp/$i
    ELCDIR=/usr/share/${FLAVOR}/site-lisp/$i

    install -m 755 -d ${ELCDIR}
    cd ${ELDIR}
    FILES=`ls -1 *.el | grep -v autoloads`
    rm -f ${ELCDIR}/*.el
    cp ${FILES} ${ELCDIR}
    cd ${ELCDIR}

    cat << EOF > path.el
(setq load-path (cons "${ELPREFIX}" (cons "${ELPREFIX}/contrib" load-path))
      byte-compile-warnings nil)
EOF
    ${FLAVOR} ${FLAGS} ${FILES} 2>&1 | gzip -9qf > CompilationLog.gz
    rm -f *.el path.el
    ( cd ${ELDIR}
        for f in *.el; do
            ln -sf ${ELDIR}/${f} ${ELCDIR}/${f}
        done
    )
done

exit 0
