#!/bin/bash
#
# Publish a single file by connecting to a daemonized Emacs instance.

if test -z "$1"; then
    echo >&2 "Error: Not enough arguments"
    exit 1
fi

file=$(echo "$1" | sed -e 's/"/\\"/g')
emacsclient --eval "(muse-ikiwiki-publish \"$file\")"
